<a href="https://colab.research.google.com/github/helenaschatz/deep-learning-challenge/blob/main/AlphabetSoupCharity_Optimization_Model2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(["EIN", "NAME"], axis=1)

application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.

application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [10]:
# Look at APPLICATION_TYPE value counts for binning

application_counts = application_df["APPLICATION_TYPE"].value_counts()
application_counts

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_counts[application_counts<500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [11]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df["CLASSIFICATION"].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [12]:
# You may find it helpful to look at CLASSIFICATION value counts >1
print(application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() > 1])

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [13]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_counts[classification_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [14]:
# Convert categorical data to numeric with `pd.get_dummies`
numeric_df = pd.get_dummies(application_df)
numeric_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [15]:
# Split our preprocessed data into our features and target arrays
y = numeric_df["IS_SUCCESSFUL"].values
X = numeric_df.drop(columns=["IS_SUCCESSFUL"]).values


# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [16]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

Compile, Train and Evaluate the Model

In [30]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = X_train_scaled.shape[1]
input_features

## (X shape/ input feature/columns is 43 * 2/3 is 86-129 so chose 100 for the first hidden node)

43

In [51]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 =  129
hidden_nodes_layer2 = 86
hidden_nodes_layers3 = 43

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layers3, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_28 (Dense)            (None, 129)               5676

 dense_29 (Dense)            (None, 86)                11180

 dense_30 (Dense)            (None, 43)                3741

 dense_31 (Dense)            (None, 1)                 44

=================================================================
Total params: 20,641
Trainable params: 20,641
Non-trainable params: 0
_________________________________________________________________

In [52]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [53]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=150)

Epoch 1/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5692 - accuracy: 0.7227
Epoch 2/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5555 - accuracy: 0.7295
Epoch 3/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5529 - accuracy: 0.7318
Epoch 4/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5509 - accuracy: 0.7320
Epoch 5/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5495 - accuracy: 0.7326
Epoch 6/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5493 - accuracy: 0.7335
Epoch 7/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7345
Epoch 8/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5475 - accuracy: 0.7358
Epoch 9/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5465 - accuracy: 0.7350
Epoch 10/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5460 - accuracy: 0.7355
Epoch 11/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7369
Epoch 12/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5456 - accuracy: 0.7358
Epoch 13/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5445 - accuracy: 0.7364
Epoch 14/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5440 - accuracy: 0.7375
Epoch 15/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5432 - accuracy: 0.7370
Epoch 16/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5434 - accuracy: 0.7375
Epoch 17/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5429 - accuracy: 0.7374
Epoch 18/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7378
Epoch 19/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5418 - accuracy: 0.7390
Epoch 20/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5420 - accuracy: 0.7378
Epoch 21/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5417 - accuracy: 0.7378
Epoch 22/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5414 - accuracy: 0.7388
Epoch 23/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5414 - accuracy: 0.7385
Epoch 24/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5409 - accuracy: 0.7387
Epoch 25/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5409 - accuracy: 0.7385
Epoch 26/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5405 - accuracy: 0.7391
Epoch 27/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5402 - accuracy: 0.7387
Epoch 28/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5397 - accuracy: 0.7393
Epoch 29/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.7392
Epoch 30/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5396 - accuracy: 0.7398
Epoch 31/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7395
Epoch 32/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5393 - accuracy: 0.7391
Epoch 33/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5386 - accuracy: 0.7397
Epoch 34/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5388 - accuracy: 0.7401
Epoch 35/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5386 - accuracy: 0.7396
Epoch 36/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5385 - accuracy: 0.7404
Epoch 37/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5384 - accuracy: 0.7409
Epoch 38/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5377 - accuracy: 0.7399
Epoch 39/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5383 - accuracy: 0.7392
Epoch 40/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5374 - accuracy: 0.7404
Epoch 41/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5377 - accuracy: 0.7403
Epoch 42/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5377 - accuracy: 0.7409
Epoch 43/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.7405
Epoch 44/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5371 - accuracy: 0.7406
Epoch 45/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5375 - accuracy: 0.7402
Epoch 46/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5374 - accuracy: 0.7397
Epoch 47/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5368 - accuracy: 0.7402
Epoch 48/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7402
Epoch 49/150
804/804 [==============================] - 4s 5ms/step - loss: 0.5370 - accuracy: 0.7406
Epoch 50/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5370 - accuracy: 0.7405
Epoch 51/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5363 - accuracy: 0.7407
Epoch 52/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5362 - accuracy: 0.7398
Epoch 53/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5363 - accuracy: 0.7402
Epoch 54/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5364 - accuracy: 0.7409
Epoch 55/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5357 - accuracy: 0.7409
Epoch 56/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7405
Epoch 57/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5358 - accuracy: 0.7402
Epoch 58/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7409
Epoch 59/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5354 - accuracy: 0.7406
Epoch 60/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5359 - accuracy: 0.7401
Epoch 61/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5353 - accuracy: 0.7405
Epoch 62/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7411
Epoch 63/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5351 - accuracy: 0.7410
Epoch 64/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5354 - accuracy: 0.7417
Epoch 65/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5355 - accuracy: 0.7406
Epoch 66/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7407
Epoch 67/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5353 - accuracy: 0.7413
Epoch 68/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5345 - accuracy: 0.7411
Epoch 69/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5344 - accuracy: 0.7412
Epoch 70/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5348 - accuracy: 0.7407
Epoch 71/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5344 - accuracy: 0.7410
Epoch 72/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5344 - accuracy: 0.7411
Epoch 73/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5351 - accuracy: 0.7406
Epoch 74/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5343 - accuracy: 0.7412
Epoch 75/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5342 - accuracy: 0.7416
Epoch 76/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5343 - accuracy: 0.7411
Epoch 77/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5339 - accuracy: 0.7414
Epoch 78/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5337 - accuracy: 0.7407
Epoch 79/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5343 - accuracy: 0.7414
Epoch 80/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5344 - accuracy: 0.7415
Epoch 81/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5335 - accuracy: 0.7413
Epoch 82/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5339 - accuracy: 0.7411
Epoch 83/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5335 - accuracy: 0.7416
Epoch 84/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5345 - accuracy: 0.7423
Epoch 85/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5334 - accuracy: 0.7413
Epoch 86/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5336 - accuracy: 0.7407
Epoch 87/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5337 - accuracy: 0.7417
Epoch 88/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5344 - accuracy: 0.7413
Epoch 89/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5353 - accuracy: 0.7412
Epoch 90/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5340 - accuracy: 0.7413
Epoch 91/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5333 - accuracy: 0.7413
Epoch 92/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5332 - accuracy: 0.7412
Epoch 93/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5333 - accuracy: 0.7421
Epoch 94/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5339 - accuracy: 0.7413
Epoch 95/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5339 - accuracy: 0.7409
Epoch 96/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5334 - accuracy: 0.7415
Epoch 97/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5339 - accuracy: 0.7420
Epoch 98/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5333 - accuracy: 0.7414
Epoch 99/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5331 - accuracy: 0.7420
Epoch 100/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5331 - accuracy: 0.7417
Epoch 101/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5335 - accuracy: 0.7416
Epoch 102/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5332 - accuracy: 0.7416
Epoch 103/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5328 - accuracy: 0.7419
Epoch 104/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5327 - accuracy: 0.7423
Epoch 105/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5330 - accuracy: 0.7416
Epoch 106/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5330 - accuracy: 0.7422
Epoch 107/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5327 - accuracy: 0.7424
Epoch 108/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5339 - accuracy: 0.7416
Epoch 109/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5332 - accuracy: 0.7423
Epoch 110/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5324 - accuracy: 0.7420
Epoch 111/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5323 - accuracy: 0.7420
Epoch 112/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5329 - accuracy: 0.7420
Epoch 113/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5321 - accuracy: 0.7413
Epoch 114/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5334 - accuracy: 0.7420
Epoch 115/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5334 - accuracy: 0.7419
Epoch 116/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5322 - accuracy: 0.7429
Epoch 117/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5324 - accuracy: 0.7423
Epoch 118/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5326 - accuracy: 0.7426
Epoch 119/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5327 - accuracy: 0.7425
Epoch 120/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5387 - accuracy: 0.7416
Epoch 121/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5327 - accuracy: 0.7428
Epoch 122/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5320 - accuracy: 0.7421
Epoch 123/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5323 - accuracy: 0.7422
Epoch 124/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5326 - accuracy: 0.7423
Epoch 125/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5324 - accuracy: 0.7425
Epoch 126/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5321 - accuracy: 0.7423
Epoch 127/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5327 - accuracy: 0.7422
Epoch 128/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5321 - accuracy: 0.7424
Epoch 129/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5330 - accuracy: 0.7415
Epoch 130/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5319 - accuracy: 0.7418
Epoch 131/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5326 - accuracy: 0.7423
Epoch 132/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5332 - accuracy: 0.7423
Epoch 133/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5317 - accuracy: 0.7429
Epoch 134/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5321 - accuracy: 0.7424
Epoch 135/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5319 - accuracy: 0.7424
Epoch 136/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5319 - accuracy: 0.7428
Epoch 137/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5322 - accuracy: 0.7428
Epoch 138/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5321 - accuracy: 0.7423
Epoch 139/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5323 - accuracy: 0.7419
Epoch 140/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5318 - accuracy: 0.7420
Epoch 141/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5355 - accuracy: 0.7421
Epoch 142/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5315 - accuracy: 0.7429
Epoch 143/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5319 - accuracy: 0.7425
Epoch 144/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5318 - accuracy: 0.7423
Epoch 145/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5316 - accuracy: 0.7426
Epoch 146/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5322 - accuracy: 0.7423
Epoch 147/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5321 - accuracy: 0.7426
Epoch 148/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5320 - accuracy: 0.7425
Epoch 149/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5323 - accuracy: 0.7425
Epoch 150/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5319 - accuracy: 0.7425

In [54]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5902 - accuracy: 0.7259 - 532ms/epoch - 2ms/step
Loss: 0.5902324318885803, Accuracy: 0.7259474992752075

In [56]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimization.h5")